version: '3'

services:
  docs:
    image: billing_counter_local_docs
    container_name: billing_counter_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./billing_counter:/app/billing_counter:z
    ports:
      - '9000:9000'
    command: /start-docs
